### ISSUE TITLE
让接口返回 R10 吧

### ISSUE THREAD

**Issue by ChinaYuanGe** [kagg886/ArcaeaB30Fucker#1]
[地址偏移.txt](https://github.com/kagg886/ArcaeaB30Fucker/files/12337107/default.txt)
搜不出来 PTT 的原因是因为 Arcaea 使用 **int32** 保存本地 PTT。

**Comment by kagg886** [comment]
不会cppTvT
https://github.com/kagg886/ArcaeaB30Fucker/blob/dev-nativePttGet/app/src/main/cpp/native-lib.cpp

**Comment by ChinaYuanGe** [comment]
不会 安卓和xposed qmq

**Comment by kagg886** [comment]
> 不会 安卓和xposed qmq

那你用cpp整合root权限内存爆搜一下ptt吧(
整合我来搞qwq...
~~你会搜内存不会xp，我会xp不会搜内存(草)~~

**Comment by ChinaYuanGe** [comment]
有没有方式交流

**Comment by kagg886** [comment]
你留个扣扣8(
