### ISSUE TITLE
在线定数表拉取失败

### ISSUE THREAD

**Issue by pvapor** [kagg886/ArcaeaB30Fucker#10]
我使用的安卓版本?

`Android 13 One UI 5.1`

我使用的是什么框架?

`LSPosed Zygisk 1.9.2`

我使用的版本?

`v1.3.3`

我使用的游戏版本?

`5.1.1c`

我遇到的问题?

`打开游戏闪退弹出在线定数表拉取失败，请重新启动Arcaea。转用 mumu模拟器12 仍然遇到一样的问题。`

**Comment by kagg886** [comment]
由于Arcaea中文维基的迁移，新域名似乎是假的https，而Arcaea的清单配置中并不支持http访问，因此造成闪退。
至于如何修复，让我康康.jpg

**Comment by kagg886** [comment]
请尝试：https://wwub.lanzouu.com/inXYq1gbmdrg
成功后请自行关闭issue

**Comment by pvapor** [comment]
尝试新发的apk后正常读取了，感谢
