### ISSUE TITLE
无法加载Native偏移量，即便使用了科学上网工具也无法加载

### ISSUE THREAD

**Issue by AkatsukiOwO** [kagg886/ArcaeaB30Fucker#12]
![Screenshot_2024-02-12-13-10-52-703_app lawnchair debug-edit](https://github.com/kagg886/ArcaeaB30Fucker/assets/154645547/5ad8d897-5ca6-4155-bb1e-875fbf112f0c)
![Screenshot_2024-02-12-13-11-21-485_app lawnchair debug-edit](https://github.com/kagg886/ArcaeaB30Fucker/assets/154645547/933d526e-b492-4298-b524-dc81616d820d)

**Comment by kagg886** [comment]
报版本，以及是否为谷歌版umm
