### ISSUE TITLE
试图查看b30时崩溃

### ISSUE THREAD

**Issue by huoyan1231** [kagg886/ArcaeaB30Fucker#2]
[Log-e8c30131-8e35-420f-83fb-a4531672a668.zip](https://github.com/kagg886/ArcaeaB30Fucker/files/12354719/Log-e8c30131-8e35-420f-83fb-a4531672a668.zip)

**Comment by kagg886** [comment]
try https://github.com/kagg886/ArcaeaB30Fucker/releases/tag/V1.1.1-pre1

**Comment by huoyan1231** [comment]
> try https://github.com/kagg886/ArcaeaB30Fucker/releases/tag/V1.1.1-pre1

仍然崩溃，且无法连接至服务端

**Comment by kagg886** [comment]
> 

重新传了一下//////，因为apply方法没写(
用新包再试一下？还不行的话，把你qq留一下(

**Comment by huoyan1231** [comment]
> > 
> 
> 重新传了一下//////，因为apply方法没写( 用新包再试一下？还不行的话，把你qq留一下(

主播你release没发文件（

**Comment by kagg886** [comment]
憋憋

**Comment by huoyan1231** [comment]
> 憋憋

感觉是服务器端有问题了
b30之后提示拉取失败，然后服务端就爆了

**Comment by kagg886** [comment]
> > 憋憋
> 
> 感觉是服务器端有问题了 b30之后提示拉取失败，然后服务端就爆了

就是服务端问题，所以在崩溃检测里加了写服务端日志的选项（）

**Comment by huoyan1231** [comment]
> > 
> 
> 就是服务端问题，所以在崩溃检测里加了写服务端日志的选项（）

那么好消息是不崩溃了
坏消息是自动log生成也没了

**Comment by kagg886** [comment]
没事，设置里有模拟崩溃(

**Comment by huoyan1231** [comment]
[Log-a583857e-86af-4443-b338-ffa1907b6823.zip](https://github.com/kagg886/ArcaeaB30Fucker/files/12355868/Log-a583857e-86af-4443-b338-ffa1907b6823.zip)

**Comment by kagg886** [comment]
好像server的log dump有点问题(
我发现我这边的日志被夹了，不知道是怎么回事
而且也根本没法复现你这边的情况
希望加个扣扣友好跤流一下)

**Comment by huoyan1231** [comment]
> 

2431491081
