### ISSUE TITLE
部分封面加载不出来

### ISSUE THREAD

**Issue by XFYPER** [kagg886/ArcaeaB30Fucker#5]
![f0082dcc42c5f9d7dabc25d00c7776a0](https://github.com/kagg886/ArcaeaB30Fucker/assets/98130008/825ec789-67e9-4031-9436-8d6ce94003b6)

**Comment by XFYPER** [comment]
> try https://wwub.lanzoue.com/itAKz1623zjc :D
用的就是1.2.0的版本，蓝奏盘里的也试了，不过并没有什么用，看了下哔哩哔哩评论区，貌似不止我一个人有这问题

**Comment by kagg886** [comment]
> > try https://wwub.lanzoue.com/itAKz1623zjc :D
> > 用的就是1.2.0的版本，蓝奏盘里的也试了，不过并没有什么用，看了下哔哩哔哩评论区，貌似不止我一个人有这问题

蓝奏的也不行？介意提供一下账号密码么？介意的话邮件发一下账密😢:`iveour@163.com`

**Comment by XFYPER** [comment]
> 

发给你了

**Comment by kagg886** [comment]
try 1.3.0
在此版本中，若部分封面加载不出来请快速来回切换(
