### ISSUE TITLE
RealPtt服务不可用

### ISSUE THREAD

**Issue by XFYPER** [kagg886/ArcaeaB30Fucker#7]
RealPtt服务不可用
更新5.0以后就这样了，不知道什么原因。
![ea905be3f60c9cc3a01da10958b4e1d2](https://github.com/kagg886/ArcaeaB30Fucker/assets/98130008/70ca9ea7-6728-4494-9bb9-8f93128ec0e8)

**Comment by kagg886** [comment]
该项目依靠内存搜索的方式获取ptt数据
负责该工作的人不在
我又不会这个
于是只能这么🕊️了😭

**Comment by kagg886** [comment]
V1.3.3 fixed
