### ISSUE TITLE
启动游戏时闪退，提示从线上配置中找不到当前版本的偏移量

### ISSUE THREAD

**Issue by XFYPER** [kagg886/ArcaeaB30Fucker#8]
![Screenshot_2023-11-23-03-30-28-499_com miui home](https://github.com/kagg886/ArcaeaB30Fucker/assets/98130008/5b0aa094-60cb-4978-a2e2-3ab8c06e5c48)

**Comment by kagg886** [comment]
只支持 **官方** **非谷歌版**（应用版本号5.1.1c）
若您的Arcaea版本过高，请尝试降级喵x
或者等待616强制升级后远程偏移量设置被我们更新

此外，如果您有足够的能力可以查找出您的Arcaea中PTT在内存中的偏移量，请按照一定格式为这个仓库PR：https://github.com/OllyDoge/ArcMemOffsets/
